### ISSUE TITLE
[Bug] Reports: M1 Native Conda Installation fails to execute reports.  `Error: There is no current event loop in thread 'Thread-3491 (execute_notebook)'.`

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3821]
The report executes but cannot execute. This behaviour is exclusive to a M1 Conda environment because switching to the x86/64 version of Conda runs the report as expected. 

```
(🦋) /reports/ $ equity --symbol INTC

Executing: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 66/66 [03:07<00:00,  2.84s/cell]
Error: There is no current event loop in thread 'Thread-3491 (execute_notebook)'.
```

**Comment by deeleeramone** [comment]
related to: #4222

**Comment by jmaslek** [comment]
did the new install resolve this ?

**Comment by deeleeramone** [comment]
ya, good call. this has been resolved.

**Comment by RobbyC231** [comment]
I seem to still be running into this issue
```
2023 Apr 04, 14:25 (🦋) /reports/ $ forecast --symbol BAC

Executing: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:18<00:00,  1.04s/cell]
Error: There is no current event loop in thread 'Thread-45 (execute_notebook)'.
```
I am using `v2.5.1` and on condo `v23.3.1`
I am launching the terminal through the SDK with openbb

**Comment by deeleeramone** [comment]
> I seem to still be running into this issue
> 
> ```
> 2023 Apr 04, 14:25 (🦋) /reports/ $ forecast --symbol BAC
> 
> Executing: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:18<00:00,  1.04s/cell]
> Error: There is no current event loop in thread 'Thread-45 (execute_notebook)'.
> ```
> 
> I am using `v2.5.1` and on condo `v23.3.1` I am launching the terminal through the SDK with openbb

Update your version to get the fixes. `pip install -U openbb[all] --no-cache-dir`

There are also nightly builds: `pip install openbb-nightly[all] --no-cache-dir`

![Screenshot 2023-04-04 at 3 06 27 PM](https://user-images.githubusercontent.com/85772166/229933265-afa1ca37-f5a3-4414-9a5a-84c00dd63fa7.png)

**Comment by RobbyC231** [comment]
I tried running both those commands to update my version but still getting that error. 
I ran the nightly build and ran into some issue with the pip and dependencies.
```bash
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openbb 2.5.1 requires ipython==8.5.0, but you have ipython 8.11.0 which is incompatible.
openbb 2.5.1 requires pycoingecko<3.0.0,>=2.2.0, but you have pycoingecko 3.1.0 which is incompatible.
openbb 2.5.1 requires pyrsistent<0.19.0,>=0.18.0, but you have pyrsistent 0.19.3 which is incompatible.
```

I am also running on an Apple M1 if that is any help

**Comment by deeleeramone** [comment]
This is fine. These are just warnings and can be ignored.
